Chore/sync upstream (#2)
* Support ~R for rekey

* Don't end strict kex until receiving newkeys

Previously non-strict packets would be allowed once Dropbear's own
SSH_MSG_NEWKEYS had been sent, but for correctness it should only be
allowed once receiving the SSH_MSG_NEWKEYS from the peer.

Reported by Fabian Bäumer

* Only report "rekey" as a trace log

* Execute multihop commands directly, no shell

This avoids problems with shell escaping if arguments contain special
characters.

* 2025.88 changelog

* Fix reference to distrooptions.h in default_options.h

The path for distribution customizations is src/distrooptions.h, not
src/distoptions.h.

This minor typo was added in 454591d (Use src/distrooptions.h as another
source, 2024-01-22).

* Fix proxycmd without netcat

fixes e5a0ef27c2 "Execute multihop commands directly, no shell"

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

* Don't run hg in configure

* Don't limit channel window to 500MB

Previously the channel window and increments were limited to 500MB.
That is incorrect and causes stuck connections if peers advertise
a large window, then don't send an increment within the first 500MB.

That's seen with SSH.NET https://github.com/sshnet/SSH.NET/issues/1671

* fix build without pubkey options

fixes:
- 98ef42a856 "Don't set pubkey_info directly in checkpubkey_line"
- 62ea53c1e5 "Implement no-touch-required and verify-requred for authorized_keys file"

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

* fix missing depends for sntrup761x25519-sha512

fixes 440b7b5c4f "Add sntrup761x25519-sha512 post-quantum key exchange"

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

* Use $(MAKE) for "make check"

Should help for non-gmake platforms

* fix: add missing signals

* Fix incorrect server auth delay

Auth delay was meant to be 250-350ms, it was actually 150-350ms or
possibly negative.
Fixes #387

* tests: Fix SO_REUSEADDR for TCP tests

Previous allow_reuse_addr was incorrect, it should be
allow_reuse_address. Confirmed looking at setsockopt in strace when
running tcpflushout test.

This is a partial fix for github #386

* Fix typo in PAM compiler error message

* Fix too small ecdsa private key buffer

When RSA or DSS are not built, the private key buffer size is too small,
resulting in a "bad_getbuf" or similar exit. This was a regression in
2025.87.
Fixes: 440b7b5c4ffb ("Add sntrup761x25519-sha512 post-quantum key exchange")

ECDSA private key requires around 241 bytes
4 + len("ecdsa-sha2-nistp521") + 4 + (521/8+1 + 4)*3 + 4

Fixes #368 on github.

* Drop privileges after user authentication

Instead of switching user privileges after forking to a shell, switch
to the user immediately upon successful authentication.

This will require further commits to fix utmp and hostkey handling.

The DROPBEAR_SVR_DROP_PRIVS configuration option controls this
behaviour.  This should generally be enabled, but can be set to 0 for
incompatible platforms.  In future it may become non-optional, those
platforms should be investigated.

Most uses of DROPBEAR_SVR_MULTIUSER have been replaced by
!DROPBEAR_SVR_DROP_PRIVS.

* Remove return code from login_login

Previously this was always 0, so not useful.

* Retain utmp saved group when dropping privileges

utmp is required to record logout. The saved group
is reset by the OS for the executed user shell.

This requires setresgid() function which is not available on all
platforms. Notable platforms are netbsd and macos. Those platforms will
have to set DROPBEAR_SVR_DROP_PRIVS 0 unless an alternative approach is
found.

* Limit rekey to current hostkey type

During rekey dropbear process may be running with user privileges, that
can't write a new hostkey when auto-generating keys.
Only offer the original hostkey when rekeying, also for non-autogenerate
case.

* fix: ignore -g -s when passwords arent enabled

* Ignore more disabled server arguments

Ignore "disable" arguments when the feature is compiled out.
-j  Disable local port forwarding
-k  Disable remote port forwarding
-m  Don't display the motd on login

* Restore seteuid for authorized_keys

Authorized_keys reading is pre-authentication so should not be
modified in the post-auth drop-privilege change.

Fixes: e0251be2354e ("Drop privileges after user authentication")

* Require dropped privileges for unix stream forward

Otherwise the stream will be created by the root user and other programs
may trust the root user via SO_PEERCRED/SO_PASSCRED

* Disallow unix stream forwarding for forced command

Being able to create a unix stream to a system may bypass forced command
restrictions, so disallow that.

* scp CVE-2019-6111 fix

Cherry-pick from OpenSSH portable

391ffc4b9d31 ("upstream: check in scp client that filenames sent during")

upstream: check in scp client that filenames sent during

remote->local directory copies satisfy the wildcard specified by the user.

This checking provides some protection against a malicious server
sending unexpected filenames, but it comes at a risk of rejecting wanted
files due to differences between client and server wildcard expansion rules.

For this reason, this also adds a new -T flag to disable the check.

reported by Harry Sintonen
fix approach suggested by markus@;
has been in snaps for ~1wk courtesy deraadt@

* Fix release script for setresgid

Script doesn't use config.h so define it manually

* 2025.89 changelog

* Fix CI builds, disable unix socket forwarding

macos doesn't currently support DROPBEAR_SVR_DROP_PRIVS so can't use
unix socket forwarding either.

Also disable it for nondefault builds.

* Avoid unused declaration with unix socket disabled

* Fix changelog typo

"fowarding"

* Update configure.ac minimum to 2.70

Previous versions don't search src/ for install.sh as a
AC_CONFIG_AUX_DIR path.

Fixes #334

* More manpage documentation for forced commands

* Improve authorized_keys manpage formatting

* Fix svr-authpubkey mixed tabs and spaces

* Fix off by one in server fail count

Setting MAX_AUTH_TRIES (or -T) to 0 is a valid configuration - it
requires the first authentication attempt to succeed.

* Limit server number of public key queries

A ssh client queries a server whether a public key will be accepted
prior to performing a real signature. Previously there was no limit on
the number of queries.

Public key queries are a user enumeration/privacy concern if an attacker
iterates with known public keys such as those published by github
(mapping to github usernames). If total privacy is required, the proper
solution is to use separate authorized_keys compared to publicly used
ones (or avoid services that publish public keys).

As a mitigation for reused public keys, Dropbear now limits to 15 public
keys attempts per session.  Public key queries start being counted as
failed authentication attempts after (MAX_AUTH_TRIES - MAX_PUBKEY_QUERIES).
This provides a rate limit on public key queries.

Reported by HD Moore, details are in the SSHamble presentation.

* server: Disallow signal with forced command

When a forced command is set it is usually to limit functionality
available to a client. Signals sent to the forced command process may
have unexpected handling, so disallow them.

* server: Disallow signal without dropping privilege

Signals were previously sent to the process with server privileges
(usually root). That may have unexpected behaviour, so disallow it.

Since 2025.89 with drop privileges the signal is now sent as the
authenticated user instead. If needed, switching the euid could be
implemented, but for the time being signals are just rejected if
dropping privileges isn't supported.

* client: check isatty when sending PTY request

Otherwise can fail with

./dbclient -i .ssh/id root@x.x.x.x << EOF
    ls
    EOF
./dbclient: Failed reading termmodes

Fixes #385

* distclean config.h not src/config.h

Generated config.h wasn't moved to src.

Fixes: e49f2012adb3 ("Move some autoconf files to src/")

* distclean also remove libtom*/Makefile

* Add S < L check to curve25519

This is required by rfc8032 and avoids signature malleability (S' = S+L
would also be accepted). That does not have any security impact on the
way it is used in SSH protocol.

The check was not present in original tweetnacl.

Fixes #406

* Check y < p in curve25519

This is required by rfc8032, otherwise a non-canonical public key
y' = y+p  could also validate. That would not pose any security
concern for SSH protocol given the public key is compared against a
fixed value during verification, so modification would fail.

Fixes #408

* Fix incorrect ssh-connection check

This would also accept other strings of the same length or prefix.

Fixes #397

* Fix incorrect index closing listeners

This could read beyond socks[] and close an arbitrary descriptor.
The codepath runs when creating TCP listeners for forwarding (client or
server).

* tests: Detect segfault in server processes

A segfault in a server child process wouldn't have been detected.
This detection is simple but seems adequate.

* Add ListenerType enum

This has no functional effect, but improves the innacurate comment on
the Listener "type" field.

* Fix cancelling server TCP listeners

There are three bugs involved here.

get_listener() only tested the first element in the list rather than
iterating.  This was incorrect when first written in
444dbb536479 ("- Reworked non-channel fd handling to listener.c - More channel cleaning up")

tcpinfo.chantype isn't initialised in svr_cancelremotetcp(), so
matchtcp() never succeeded. The chantype comparison is unnecessary
(LISTENER_TYPE_TCPFORWARDED has already been checked), so remove it.

matchtcp() was comparing with listenaddr, but that will be NULL
when listening on localhost, logic in svr_remotetcpreq().
That regressed in 1984aabc9509 ("Server shouldn't return "localhost" in response to -R forward connections if that wasn't what the client requested.")
The NULL pointer previously couldn't be reached due to the chantype
problem mentioned above.

A testcase is added.

Fixes #412, fixes #413

* Rework pubkey_options struct

Pubkey info is now included in the restriction struct. A temporary
pubkey_options is filled then set in the global session after auth.

* Fix update_timeout check

Already elapsed time was being added rather than subtracted to
the remaining time. This could result in timeouts occurring later than
expected.

* server: change auth timeout checking dependency

Use authdone instead of connect_time as dependency for authentication
timeout checking. This prevents connect_time from being set to 0
unnecessarily and allows it to be used for other purposes.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

* Add new parameter -M for max. duration

Some technical guidelines (e.g., TR-03148) and cybersecurity baselines
require a hard maximum connection duration / session timeout for remote
connections. Therefore, a parameter is hereby introduced that can be
used to configure the maximum connection duration. The default value is
0 (disabled).

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

* tests: Fix DEFAULT_MAX_DURATION=0 becoming 1

nondefault option tests changes all 0 options to 1, but that results in
a 1 second timeout so the test fails.

* Github actions complains about checkout v4

Use checkout@v6, upload-artifact@v7

* server: open authorized_keys files nonblocking

This avoids getting stuck with special files.

* Handle agent listener when fuzzing

Using a real listener socket caused an assertion in the fuzz harness.
https://issues.oss-fuzz.com/issues/470230567

* Add support for permitlisten to authorized_keys

* Reword permitlisten to avoid "source"

The bind/listen address is what should be used. "Source" could be
confused with the originating TCP host connecting to a listener.

* Only accept a port for permitlisten

For the time being a plain permitlisten="port" is adequate.

Host support is more complicated with various special hostnames of "*"
or "localhost", "127.0.0.1", "::1", etc. There are also interactions
with "-a"/GatewayPorts.

* Support for remote forwarding with unix sockets

(rebased with minimal compile fixes by Matt Johnston)

* remote unixfwd: More checks, adapt for drop privs

Since the remote stream forward code was written, Dropbear now drops
privileges. The seteuid() etc can be removed. Stream forwarding
isn't allowed when privilege dropping is disabled.

Stream listeners are disallowed when a forced command is in effect - a
unix socket in certain user-writable locations could possibly bypass
command restrictions.

* remote unixfwd: Always unlink existing socket

The streamlocalbindunlink setting is now always enabled - having to rely
on external mechanisms to clean up stale sockets is awkward.

* server: -c help text was hidden without remote TCP

* Rename tcpfwd filename to forward

Now handles stream forwarding as well

* Split tcp and stream forwarding files

This mainly affects server handling.
TcpListener is renamed to FwdListener, svr-tcpfwd.c is split into
svr-forward.c, svr-tcpfwd.c, and svr-streamfwd.c

* server tcp forward: send replies correctly

tcpip-forward requests should only send a response when wantreply
request flag is set. The port should only be included when a port is
allocated by the server.

* ci: build on push for all branches

* ci: "all branches" also for outoftree and autoconf

* scp: more CVE-2019-6111 fix

Cherrypicked from OpenSSH portable

commit 3d896c157c722bc47adca51a58dca859225b5874
djm Sun Feb 10 11:15:52 2019 +0000

upstream: when checking that filenames sent by the server side

match what the client requested, be prepared to handle shell-style brace
alternations, e.g. "{foo,bar}".

"looks good to me" millert@ + in snaps for the last week courtesy
deraadt@

* scp: Disallow -r to an existing directory

Checks of received paths don't catch all cases in -r recursive mode, so
disallow -r when the destination directory exists. This mitigates
CVE-2019-6111, where unexpected files would be accepted from a malicious
scp server.

Alternatives like rsync could be used in that case.

The new error message may be misleading if parent path components of the
destination are also missing, though the command would have failed
regardless.

* scp: clear setuid/setgid bits on received files

From openssh-portable 487e8ac146f7d6616f65c125d5edb210519b833a
Tracked as CVE-2026-35385

upstream: when downloading files as root in legacy (-O) mode and

without the -p (preserve modes) flag set, clear setuid/setgid bits from
downloaded files as one might expect.

AFAIK this bug dates back to the original Berkeley rcp program.

Reported by Christos Papakonstantinou of Cantina and Spearbit.

OpenBSD-Commit-ID: 49e902fca8dd933a92a9b547ab31f63e86729fa1

* manpage: Add dropbear -M session timeout option

* scp: Avoid compile warnings

* Add m_mp_burn()

* Implement RSA exponent blinding

Reduces a timing side-channel in the RSA signing operation.

RSA keys generated with Dropbear < 0.33 are no longer supported, since
the necessary P and Q values are not stored. That release was in 2004,
it is unlikely keys are still in use.

* Release 2026.90

* scp: don't use reallocarray

reallocarray() isn't portable. An overflow check can be used instead.

Fixes: 143291baca6e ("scp: more CVE-2019-6111 fix")

* scp: fix recursive overwrite check

Non-recursive transfers were incorrectly disallowed to an existing
destination.

In addition, the destination check logic was wrong.

Fixes: 61bd0e3e6573 ("scp: Disallow -r to an existing directory")

* ci: build scp

* Revert "ci: build scp"

PROGRESS_METER conditional causes
    error: variable 'statbytes' set but not used

This reverts commit de87f98c0e15fb6ab897566f77acce1778d613a5.

* client: Disable compression by default

Compression can be enabled with -o compression=y
or with compile time DROPBEAR_CLI_COMPRESSION option.

* Allow y/n for -o options

* Add -Q to query supported algorithms

Run by itself it will print the algorithms specified at compile time.
For the client the lists will be modified by "-o Compression" or -c/-m
arguments.

* Manpage doc for dbclient -o compression

* Release 2026.91

* Improve confusing wording in CHANGES

The entry doesn't refer to a test (unit test etc), but rather to logic
in an "if" statement.

* sntrup: Fix 64-bit literals

Avoids warning on 32-bit platform

src/sntrup761.c:1643: warning: integer constant is too large for 'long' type

* Local debian packaging: don't set CC for make

On old platforms where gcc requires a -std=gnu99 argument for c99
support, the configure script detects that and adds it to CC.
Setting CC back to "gcc" in debian/rules reverts that, so
sntrup761/mlkem fail to compile.

The whole tarball debian/ directory is ancient and unmaintained, but is
kept since it is still being used on old distros.

Upstream debian packaging should be used where possible, thanks to
Guilhem Moulin and prior Debian maintainers.

* Increase MAX_HOSTKEYS to 6

This allows all key types to be loaded at once, including different
ecdsa sizes.
Suggested by Darren Tucker.

* Fix spelling in CHANGES

* Suggest libcrypt-dev for crypt()

Recent glibc doesn't include crypt(), it's now provided by libxcrypt.

* Fix too-low pubkey key query count

Dropbear 2026.90 added a limit to the number of queries that could be
made to a server when determining usable keys. This was intended to be
set to 15 (MAX_PUBKEY_QUERIES) but the logic was incorrect (and also
debug code was accidentally committed). This meant only 10 (default
MAX_AUTH_TRIES/-T) tried keys would be allowed - not a huge difference.

Reported by Rui Salvaterra

Fixes: db0d3fd0a9e9 ("Limit server number of public key queries")

---------

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>
Signed-off-by: Martin Schiller <ms@dev.tdt.de>
Co-authored-by: Matt Johnston <matt@ucc.asn.au>
Co-authored-by: Todd Zullinger <tmz@pobox.com>
Co-authored-by: Konstantin Demin <rockdrilla@gmail.com>
Co-authored-by: Loïc Mangeonjean <loic@coderpad.io>
Co-authored-by: Norbert Lange <norbert.lange@andritz.com>
Co-authored-by: Martin Schiller <ms@dev.tdt.de>
Co-authored-by: Mitar <mitar.git@tnode.com>
Co-authored-by: Brian Dentino <brian@tno.me>